---
title: "Heatmap of the PRSs matrices"
output: github_document
author: Amin Kharaghani
date: Jan 27, 2020
output:
  github_document:
    html_preview: true
    toc: true
    toc_depth: 3
---
```{r setup, include=FALSE}
library(data.table)
library(openxlsx)
library(rms)
library(limma)
library(ggplot2)
library(factoextra)
library(diptest)
library(corrplot)
library(dendextend)

ROSmaster <- readRDS("/Users/amink/OneDrive/Documents/Current Jobs/Masters Thesis/Code/Datasets/ROSMAP_Phenotype/ROSmaster.rds")

# Will change this later
meta_pheno <- read.csv("/Users/amink/OneDrive/Documents/Current Jobs/Masters Thesis/Code/Master_Thesis/Pan_UKBB/OLD/ukbb_manifest_EUR_h2_05_both_sex_annotated.csv")

geno_pcs <- read.table("/Users/amink/OneDrive/Documents/Current Jobs/Masters Thesis/Code/Datasets/PCA_Genotype/geno_qc.eigenvec.txt",header=F)
names(geno_pcs) <- c("FID","IID",paste0("genoPC",seq(1:10)))

prs_filenames <- list.files("/Users/amink/OneDrive/Documents/Current Jobs/Masters Thesis/Code/Datasets/PRS_PLINK_Resid_PCA_Clust/",full.names = T)

# read in PRS files
results1 <- list()
for (prsfile in prs_filenames[1:10]) {
  results1[[tail(strsplit(prsfile,split="/")[[1]],n=1)]] <- readRDS(prsfile)
}
```


```{r hm, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
for(prs_matrix in names(results1)){
                jpeg(paste0("/Users/amink/OneDrive/Documents/Current Jobs/Masters Thesis/Code/Master_Thesis/Plots/Heatmaps/Heatmap_Pheno_",
                                            gsub("PCAresults_","",gsub(".rds","",prs_matrix)),".jpg"),
                                     width = 1200, height = 1500)
                heatmap(as.matrix(results1[[prs_matrix]]$residuals[,-dim(as.matrix(results1[[prs_matrix]]$residuals))[2]]))
                dev.off()
}
``` 
