---
title: "Hierarchical Clustering of the PRSs matrices"
output: github_document
---

```{r setup, include=FALSE}
library(data.table)
library(openxlsx)
library(rms)
library(limma)
library(ggplot2)
library(factoextra)
library(diptest)
library(corrplot)
library(dendextend)

ROSmaster <- readRDS("/Users/amink/OneDrive/Documents/Current Jobs/Masters Thesis/Code/Datasets/ROSMAP_Phenotype/ROSmaster.rds")

meta_pheno <- read.csv("/Users/amink/OneDrive/Documents/Current Jobs/Masters Thesis/Code/Datasets/Sum_Stats/Pan_UK_Biobank_phenotype_manifest_h2_more_0.05_both_sex_non_ambigous.csv")

geno_pcs <- read.table("/Users/amink/OneDrive/Documents/Current Jobs/Masters Thesis/Code/Datasets/PCA_Genotype/geno_qc.eigenvec.txt",header=F)
names(geno_pcs) <- c("FID","IID",paste0("genoPC",seq(1:10)))

prs_filenames <- list.files("/Users/amink/OneDrive/Documents/Current Jobs/Masters Thesis/Code/Datasets/PRS_PLINK_Resid_PCA_Clust/",full.names = T)

# read in PRS files
results1 <- list()
for (prsfile in prs_filenames[1:10]) {
  results1[[tail(strsplit(prsfile,split="/")[[1]],n=1)]] <- readRDS(prsfile)
}
```

# Hierarchical Clustering

First, we create clusters of the residuals matrix for both individuals and phenotypes.



We take a look at the Dendogram of the phenotypes of the residuals of the PRSs.

```{r dd, fig.align='center', fig.height=100, fig.show='animate', fig.width=50, cache=FALSE, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
op <- par(mfrow=c(1,2), mar=c(3,1,1,1))
for(prs_matrix in names(results1)){
                clusters <- results1[[prs_matrix]]$clust.var
                dend <- as.dendrogram(clusters)
                # order it the closest we can to the order of the observations:
                dend <- rotate(dend, 1:length(clusters$labels))
                # Color the branches based on the clusters:
                dend <- color_branches(dend, k = 3) #, groupLabels=iris_species)
                # We hang the dendrogram a bit:
                dend <- hang.dendrogram(dend, hang_height = 0.1)
                # reduce the size of the labels:
                dend <- set(dend, "labels_cex", 0.5)
                # And plot:
                par(mar = c(3, 3, 3, 7))
                if(prs_matrix == 'PCAresults_p_val_1.rds'){
                                jpeg(paste0("/Users/amink/OneDrive/Documents/Current Jobs/Masters Thesis/Code/Master_Thesis/Plots/Dendogram_",
                                            gsub("PCAresults_","",gsub(".rds","",prs_matrix)),".jpg"),
                                     width = 1000, height = 1200)
                                plot(dend, cex.main=1,
                                     main =paste0('Dendogram of PRSs of phenotypes of ',
                                                  dim(matrix)[1],' individuals',"\n",
                                                  'at P-value threshold of ',
                                                  unlist(strsplit(prs_matrix, "[_.]"))[4]),
                                     horiz =  TRUE,
                                     nodePar = list(cex = .007)
                                )
                                dev.off()
                                # circlize_dendrogram(dend)
                                
                } else {
                                jpeg(paste0("/Users/amink/OneDrive/Documents/Current Jobs/Masters Thesis/Code/Master_Thesis/Plots/Dendogram_",
                                            gsub("PCAresults_","",gsub(".rds","",prs_matrix)),".jpg"),
                                     width = 1000, height = 1200)
                                plot(dend, cex.main=1,
                                     main =paste0('Dendogram of PRSs of phenotypes of ',
                                                  dim(matrix)[1],' individuals',"\n",
                                                  'at P-value threshold of ',
                                                  paste0(unlist(strsplit(prs_matrix, "[_.]"))[4],'.',
                                                         unlist(strsplit(prs_matrix, "[_.]"))[5])),
                                     horiz =  TRUE,
                                     nodePar = list(cex = .007)
                                )
                                dev.off()
                                # circlize_dendrogram(dend)
                }
}
par(op)
                                                      
```


We take a look at the Dendogram of the phenotypes of the residuals of PRSs at an individual level.

```{r dd1, fig.align='center', fig.height=100, fig.show='animate', fig.width=50, cache=FALSE, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
op <- par(mfrow=c(1,2), mar=c(3,1,1,1))
for(prs_matrix in names(results1)){
                clusters <- results1[[prs_matrix]]$clust.ind
                dend <- as.dendrogram(clusters)
                # order it the closest we can to the order of the observations:
                dend <- rotate(dend, 1:length(clusters$labels))
                # Color the branches based on the clusters:
                dend <- color_branches(dend, k = 3) #, groupLabels=iris_species)
                # We hang the dendrogram a bit:
                dend <- hang.dendrogram(dend, hang_height = 0.1)
                # reduce the size of the labels:
                dend <- set(dend, "labels_cex", 0.5)
                # And plot:
                par(mar = c(3, 3, 3, 7))
                if(prs_matrix == 'PCAresults_p_val_1.rds'){
                                jpeg(paste0("/Users/amink/OneDrive/Documents/Current Jobs/Masters Thesis/Code/Master_Thesis/Plots/Dendogram_",
                                            gsub("PCAresults_","",gsub(".rds","",prs_matrix)),".jpg"),
                                     width = 1000, height = 1200)
                                plot(dend, cex.main=1,
                                     main =paste0('Dendogram of PRSs of individuals of ',
                                                  dim(matrix)[1],' individuals',"\n",
                                                  'at P-value threshold of ',
                                                  unlist(strsplit(prs_matrix, "[_.]"))[4]),
                                     horiz =  TRUE,
                                     nodePar = list(cex = .007)
                                )
                                dev.off()
                                # circlize_dendrogram(dend)
                                
                } else {
                                jpeg(paste0("/Users/amink/OneDrive/Documents/Current Jobs/Masters Thesis/Code/Master_Thesis/Plots/Dendogram_",
                                            gsub("PCAresults_","",gsub(".rds","",prs_matrix)),".jpg"),
                                     width = 1000, height = 1200)
                                plot(dend, cex.main=1,
                                     main =paste0('Dendogram of PRSs of individuals of ',
                                                  dim(matrix)[1],' individuals',"\n",
                                                  'at P-value threshold of ',
                                                  paste0(unlist(strsplit(prs_matrix, "[_.]"))[4],'.',
                                                         unlist(strsplit(prs_matrix, "[_.]"))[5])),
                                     horiz =  TRUE,
                                     nodePar = list(cex = .007)
                                )
                                dev.off()
                                # circlize_dendrogram(dend)
                }
}
par(op)
```
